currentslice.user=<username>
currentslice.password=<password>
currentslice.dbName=<dbName>
currentslice.host=<host>
currentslice.port=<mySQLPort>

previousslice.user=<username>
previousslice.password=<password>
previousslice.dbName=<dbName>
previousslice.host=<host>
previousslice.port=<mySQLPort>

personId=<personDbId>
uploadToSource=<true/false>

